// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package ws

import (
	"github.com/gorilla/websocket"
	"im-chat/api/ws"
	"im-chat/internal/logic/chat"
	"net/http"
)

type ControllerV1 struct {
	upgrader    *websocket.Upgrader
	chatManager *chat.ChannelManager
}

func NewV1() ws.IWsV1 {
	return &ControllerV1{
		upgrader: &websocket.Upgrader{
			CheckOrigin: func(r *http.Request) bool {
				return true
			},
		},
		chatManager: chat.NewChannelManager(),
	}
}
