// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package cmd

import (
	"im-chat/internal/controller/auth"
	"im-chat/internal/controller/friend"
	"im-chat/internal/controller/room"
	"im-chat/internal/controller/user"
	"im-chat/internal/controller/ws"
	"im-chat/internal/logic/chat"
)

// Injectors from wire.go:

func InjectorApp() (*App, error) {
	iAuthV1 := auth.NewV1()
	noAuthServer := NewNoAuthServer(iAuthV1)
	iUserV1 := user.NewV1()
	channelManager := chat.NewChannelManager()
	iWsV1 := ws.NewV1(channelManager)
	iRoomV1 := room.NewV1()
	iFriendV1 := friend.NewV1()
	authServer := NewAuthServer(iUserV1, iWsV1, iRoomV1, iFriendV1)
	app := NewApp(noAuthServer, authServer)
	return app, nil
}
