// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package friend

import (
	"im-chat/api/friend"
)

type ControllerV1 struct{}

func NewV1() friend.IFriendV1 {
	return &ControllerV1{}
}
