// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"im-chat/internal/dao/internal"
)

// internalChatMessageDao is an internal type for wrapping the internal DAO implementation.
type internalChatMessageDao = *internal.ChatMessageDao

// chatMessageDao is the data access object for the table chat_message.
// You can define custom methods on it to extend its functionality as needed.
type chatMessageDao struct {
	internalChatMessageDao
}

var (
	// ChatMessage is a globally accessible object for table chat_message operations.
	ChatMessage = chatMessageDao{
		internal.NewChatMessageDao(),
	}
)

// Add your custom methods and functionality below.
