// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"im-chat/internal/dao/internal"
)

// internalRoomDao is an internal type for wrapping the internal DAO implementation.
type internalRoomDao = *internal.RoomDao

// roomDao is the data access object for the table room.
// You can define custom methods on it to extend its functionality as needed.
type roomDao struct {
	internalRoomDao
}

var (
	// Room is a globally accessible object for table room operations.
	Room = roomDao{
		internal.NewRoomDao(),
	}
)

// Add your custom methods and functionality below.
