// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"im-chat/internal/dao/internal"
)

// internalUserFriendRelationDao is an internal type for wrapping the internal DAO implementation.
type internalUserFriendRelationDao = *internal.UserFriendRelationDao

// userFriendRelationDao is the data access object for the table user_friend_relation.
// You can define custom methods on it to extend its functionality as needed.
type userFriendRelationDao struct {
	internalUserFriendRelationDao
}

var (
	// UserFriendRelation is a globally accessible object for table user_friend_relation operations.
	UserFriendRelation = userFriendRelationDao{
		internal.NewUserFriendRelationDao(),
	}
)

// Add your custom methods and functionality below.
