// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"im-chat/internal/dao/internal"
)

// internalUserRoomRelationDao is an internal type for wrapping the internal DAO implementation.
type internalUserRoomRelationDao = *internal.UserRoomRelationDao

// userRoomRelationDao is the data access object for the table user_room_relation.
// You can define custom methods on it to extend its functionality as needed.
type userRoomRelationDao struct {
	internalUserRoomRelationDao
}

var (
	// UserRoomRelation is a globally accessible object for table user_room_relation operations.
	UserRoomRelation = userRoomRelationDao{
		internal.NewUserRoomRelationDao(),
	}
)

// Add your custom methods and functionality below.
